services:
  - type: web
    name: gm-scraper
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: gm-scraper-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: TZ
        value: UTC

databases:
  - name: gm-scraper-db
    databaseName: gm_scraper
    user: gm_scraper_user
    plan: free
    region: frankfurt
