services:
- type: web
  name: headlinehub
  runtime: node
  repo: https://github.com/jengahmedeyan/headlinehub
  plan: free
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: ELEVENLABS_API_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
  startCommand: npm start
  autoDeployTrigger: commit
version: "1"