services:
- type: web
  name: headlinehub
  runtime: node
  repo: https://github.com/jengahmedeyan/headlinehub
  plan: free
  envVars:
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: ELEVENLABS_API_KEY
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node dist/app.js
  autoDeployTrigger: commit
version: "1"
