name: Scheduled News Scraping

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npx prisma generate
      
      - name: Run news scraping
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node -e "
          const { RssScraperService } = require('./dist/services/rss-scraper.service');
          RssScraperService.scrapeAndSaveAllRssNews()
            .then(() => {
              console.log('✅ Scheduled RSS news scraping complete.');
              process.exit(0);
            })
            .catch((error) => {
              console.error('❌ Scraping failed:', error);
              process.exit(1);
            });
          "
      
      - name: Trigger API endpoint (optional)
        run: |
          curl -X POST "${{ secrets.VERCEL_URL }}/api/operations/scrape" \
            -H "Content-Type: application/json" \
            -d '{"source": "github-actions"}' || true